on:
  schedule:
    # around 7:30am on mondays
    - cron: "27 14 * * 1"
  workflow_dispatch:
    inputs:
      until-version:
        description: 'The version to stop at (not including this one)'
      max-count:
        type: number
        description: 'Max number of versions to create'
jobs:
  fetch_new_commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # actions/checkout sets up git credentials but not commit author
          # https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
          # This email address is a valid user in the github gui
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # https://github.community/t/github-actions-bot-email-address/17204/5
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: node .download-changes/download-changes-and-create-commits.mjs ${UNTIL_VERSION:+--until-version=$UNTIL_VERSION} ${MAX_COUNT:+--max-count=$MAX_COUNT}
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          UNTIL_VERSION: ${{ github.event.inputs.until-version }}
          MAX_COUNT: ${{ github.event.inputs.max-count }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
